/**
 * DEF: CALCULA A FREQUENCIA DOS ELEMENTOS NO ARQUIVO
 *
 * @param arquivo --- ARQUIVO A TER SEUS ELEMENTOS CONTADOS
 * @return unsigned int --- RETORNA UMA LISTA COM A QUANTIDADE DE CADA ELEMENTO
 */
unsigned int *freq(FILE *arquivo);
